[package]
name = "memcardpro-sync"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
lazy_static = "1.5.0"
main_error = "0.1.2"
sqlite = "0.37.0"
thiserror = "2.0.17"
